name: AutoDeploy
on:
    push:
        branches:
            - main

jobs:
    deploy:
      name: Deploying App
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: '16'
          - name: Install packages
            run: npm i
          - name: Set Creds
            run: git config user.name "pndrckr" && git config user.email "pndrckr@mail"
          - name: Deploy...
            run: npm run deploy
